---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
require(ggplot2) 
require(plyr)
require(graphics)

fileRead <- na.omit(read.csv('activity.csv', header = TRUE, na.strings = "NA"))
dayAggregate <- aggregate(fileRead$steps, list(date = fileRead$date), sum)
colnames(dayAggregate) <- c("dates", "steps")


```

## What is mean total number of steps taken per day?

```{r}
dayAggregate$dates <- as.Date(dayAggregate$dates, "%Y-%m-%d")

dayAggregate$steps <- as.numeric(dayAggregate$steps)

#head(dayAggregate)

#lapply(dayAggregate,colnames)

dates <- dayAggregate$dates
steps <- dayAggregate$steps
qplot(dates, steps)
summary(dayAggregate)
```


## What is the average daily activity pattern?
```{r}
stepAggregate <- aggregate(fileRead$steps, list(interval = fileRead$interval), mean)
colnames(stepAggregate) <- c("interval", "averageSteps")
plot(stepAggregate$interval, stepAggregate$averageSteps, type="l", xlab = "5-minute intervals", ylab = "Average number of steps taken")
summary(stepAggregate)
aggregate(stepAggregate$interval, list(averageSteps = stepAggregate$averageSteps, max))
maximumAverage <- arrange(stepAggregate, stepAggregate$averageSteps, decreasing = TRUE)
head(maximumAverage,1)
```



## Imputing missing values




## Are there differences in activity patterns between weekdays and weekends?
